baseURL: https://mariana-pino-tello.netlify.app/
languageCode: en-us
title: Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hola! Welcome to my personal website!
    My name is Mariana and I am a peruvian MFA student at London Business School
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Baker Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mpinotello.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+51) 969-948191
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
       # label: Twitter
        #url: https://www.twitter.com
      #- icon: fa-facebook
       # label: Facebook
        #url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/marianapinotello/
      - icon: fa-github
        label: GitHub
        url: https://github.com/MarianaPinoTello
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/marianapino/
  image: ''
  name: Mariana Pino Tello
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Who am I?
        title: About me
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Know a bit more about my R projects
        title: My Projects
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Know more about my company
        title: My company
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Some of my favourites places
        title: Places I've visited
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Learn about Peru!
        title: My country
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Learn about my experience
        title: My CV
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
