baseURL: https://mariana-pino-tello.netlify.app/
languageCode: en-us
title: Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: Thanks for being here. My name is Mariana and I am a peruvian MFA student at London Business School
    title: Hola! Welcome to my personal website!
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Baker Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mpinotello.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+51) 969-948191
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
       # label: Twitter
        #url: https://www.twitter.com
      #- icon: fa-facebook
       # label: Facebook
        #url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/marianapinotello/
      - icon: fa-github
        label: GitHub
        url: https://github.com/MarianaPinoTello
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/marianapino/
  image: ''
  name: Mariana Pino Tello
  navigation:
    button1:
      - name: Leaarn more about me
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
    #  - name: Elements
     #   url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Learn about LBS
        title: Life at LBS
        url: blogs/aliquam
      - image: MP9.jpg
        subtitle: Learn more about me
        title: About me
        url: blogs/tempus
      - image: gris.jpg
        subtitle: Know more about my company
        title: Gris Papeleria
        url: blogs/magna
      - image: r.png
        subtitle: Some of my past projects
        title: My R projects
        url: blogs/ipsum
      - image: peru.jpg
        subtitle: Learn about Peru!
        title: My country
        url: blogs/ipsum
      - image: MP7.jpg
        subtitle: Learn about my experience
        title: My CV
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Gracias! Thanks for visiting my website! If you have any questions or is there anything I can do to help, please do not hesitate to contact me through social media.
      \n    Or just drop me an email or send me a text message and we can grab a coffee!"
    title: Nice having you here
    url: blogs
